Models/CRUDDBContext.cs
using Microsoft.EntityFrameworkCore;
using System;

namespace ASP.NETCore.Models
{
    public class CRUDDBContext : DbContext
    {
        public CRUDDBContext(DbContextOptions<CRUDDBContext> options) : base(options)
        {
            
        }

        public DbSet<Employee> Employees { get; set; }

    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace ASP.NETCore.Models
{
    public class Employee
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please provide name!")]
        [MaxLength(length: 50)]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please provide Email!")]
        public string Email { get; set; }
        public string Department { get; set; }
        public string Picture { get; set; }
    }
}

Models/EmployeeViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NETCore.Models
{
    public enum Departments
    {
        IT,
        HR,
        BPO,
        Chemistry,
        None
    }
    public class EmployeeViewModel
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public IEnumerable<IFormFile> Picture { get; set; }
    }
}

Controllers/CRUDController.cs
using ASP.NETCore.Models;
using ASP.NETCore.Repos;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.NETCore.Controllers
{
    public class CRUDController : Controller
    {
        private readonly CRUDDBContext cRUDDBContext;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IConfiguration _configuration;
        private readonly CRUDEmployee _cRUDEmployee;
        public CRUDController(CRUDDBContext cRUDDBContext, IHostingEnvironment hostingEnvironment, IConfiguration configuration)
        {
            this.cRUDDBContext = cRUDDBContext;
            this._hostingEnvironment = hostingEnvironment;
            this._configuration = configuration;
            _cRUDEmployee = new CRUDEmployee(this.cRUDDBContext, _hostingEnvironment);
        }

        public IActionResult Index()
        {
            return View();
        }

        public ViewResult CreateEmployee()
        {
            return View();
        }

        [HttpPost]
        public ViewResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                _cRUDEmployee.CreateEmployee(employee);
            }
            return View("CreateEmployee");
        }

        [HttpGet]
        public ViewResult GetAllEmployees()
        {
            return View("EmployeesList", _cRUDEmployee.GetAllEmployees());
        }

        [HttpGet]
        public ViewResult EditEmployee(int id)
        {
            return View("CreateEmployee", _cRUDEmployee.GetEmployeeOnId(id));
        }

        [HttpGet]
        public ViewResult DeleteEmployee(int id)
        {
            _cRUDEmployee.DeleteEmployee(id);
            return View("EmployeesList", _cRUDEmployee.GetAllEmployees());
        }

        [HttpPost]
        public ViewResult UpdateEmployee(Employee employee)
        {
            _cRUDEmployee.UpdateEmployee(employee);

            return View("EmployeesList", _cRUDEmployee.GetAllEmployees());
        }

    }
}

Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppName</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AppName</a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - AppName</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/CRUD/CreateEmployee.cshtml
@model EmployeeViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Create Employee";
}

<h1>Create Employee</h1>

<h4>Employee</h4>
<hr />
<form enctype="multipart/form-data" asp-action="Create" asp-controller="CRUD" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="form-group col-md-3">
            <label asp-for="Name" class="control-label">Name</label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger">@*Please Provide Name*@</span>
        </div>
        <div class="col-md-9"></div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="form-group col-md-3">
            <label asp-for="Email" class="control-label">Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger">@*Please Provide Email*@</span>
        </div>
        <div class="col-md-6"></div>
    </div>
    <div class="row">
        <div class="form-group col-md-6"></div>
        <div class="form-group col-md-3">
            <label asp-for="Department" class="control-label">Department</label>
            <select asp-for="Department" class="form-control" asp-items="Html.GetEnumSelectList<Departments>()">
                <option value="">Select Department</option>
            </select>
            <span asp-validation-for="Department" class="text-danger"></span>
            <div class="col-md-3"></div>
        </div>
    </div>
    <div class="row">
        <div class="custom-file col-md-9"></div>
        <div class="col-md-3">
            <label asp-for="Picture" class="control-label">Image</label>
            <input asp-for="Picture" accept=".png, .jpg, .jpeg" class="form-control custom-file-input" />
        </div>
    </div>

    <div class="row">
        <div class="form-group col-md-4"></div>
        <div class="form-group col-md-4"></div>
        <div class="form-group col-md-4">
            @if (Model == null)
            {
                <input type="submit" value="Create" class="btn btn-primary" />
            }
            else
            {
                <input type="submit" value="Update" asp-action="UpdateEmployee" class="btn btn-primary" />
            }
        </div>
    </div>
</form>

<div>
    <a asp-action="GetAllEmployees" asp-controller="CRUD">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CRUD/EmployeesList.cshtml
@model IEnumerable<Employee>

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        * {
            box-sizing: border-box;
        }

        #myInput {
            background-image: url('/css/searchicon.png');
            background-position: 10px 10px;
            background-repeat: no-repeat;
            width: 100%;
            font-size: 16px;
            padding: 12px 20px 12px 40px;
            border: 1px solid #ddd;
            margin-bottom: 12px;
        }

        #myTable {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #ddd;
            font-size: 18px;
        }

        #myTable th, #myTable td {
                text-align: left;
                padding: 12px;
            }

        #myTable tr {
                border-bottom: 1px solid #ddd;
            }

        #myTable tr.header, #myTable tr:hover {
                    background-color: #f1f1f1;
                }

        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
</head>
<body>

    <h2>Employees</h2>

    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">

    <table id="myTable">
        <tr class="header">
            <th>Name</th>
            <th>Email</th>
            <th>Department</th>
            <th colspan="2" style="text-align:center;">Actions</th>
        </tr>
        @foreach (Employee employee in Model)
        {
            <tr>
                <td>@employee.Name</td>
                <td>@employee.Email</td>
                <td>@employee.Department</td>
                <td>
                    <a asp-controller="CRUD" asp-action="EditEmployee" asp-route-id="@employee.Id">Edit</a>
                </td>
                <td>
                    <a asp-controller="CRUD" asp-action="DeleteEmployee" asp-route-id="@employee.Id">Delete</a>
                </td>
            </tr>
        }
    </table>

    <div> <a asp-action="CreateEmployee" asp-controller="CRUD">Create Form</a> </div>

    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>

</body>
</html> 

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts")
</body>
</html>